### ISSUE TITLE
REPACK AFTER UNPACKING?

### ISSUE THREAD

**Issue by 3316556** [klensy/wt-tools#10]
Is there any way to repack a vromfs after unpacking? I may have found a way around the file checking process.

**Comment by klensy** [comment]
In theory - yes, but at the end of file exist checksum, that i can't generate yet.

**Comment by 3316556** [comment]
by the way im working on adding helicopters from apache:air assult (one of gaijins old games) to warthunder. the game uses the same file format and the same engine (dagor) unfortunatly i had to torrent the game because gaijin closed the site that would let you download the game. the good news is i was able to get a working copy of it. the bad news is your unpacker does not work. i had to use the wtextractor from the forums to get the dxp.bin of the helicopters to decompile. all i need now is the fm of the helicopters which i have not located yet but if you want ill keep you posted.. i did not want to put this on the official forums because gaijin might not like that i found their hidden game.

**Comment by 3316556** [comment]
https://github.com/JudgeZetsumei/WarThunderShellGuide dont know what this does but it looked like it might be usefull to you
