### ISSUE TITLE
Found something that might help Extracting models,skeletons.etc from warthunder.

### ISSUE THREAD

**Issue by 3316556** [klensy/wt-tools#11]
http://imgur.com/P5pdFrQ
[plugins.zip](https://github.com/klensy/wt-tools/files/110314/plugins.zip)

**Comment by 3316556** [comment]
found these in the warthunder cdk folder these are plugins for the asset viewer that CAN export models but the devs disabled it.

**Comment by Jackaroo05** [comment]
Sorry for the necro, but how do I use this? It says the zip is invalid when extracting both with win 10 default and 7zip

**Comment by PTLD93** [comment]
> Sorry for the necro, but how do I use this? It says the zip is invalid when extracting both with win 10 default and 7zip

you need to use zip.rar and you need to extract the files on WarThunderCDK\dagor3_cdk\bin64\plugins

**Comment by auggeythecat** [comment]
> Sorry for the necro, but how do I use this? It says the zip is invalid when extracting both with win 10 default and 7zip

You just rename the file to plugins.rar and you can open and extract it. You might need to enable file extensions though.
