### ISSUE TITLE
Распаковка clog

### ISSUE THREAD

**Issue by painka** [klensy/wt-tools#12]
Как распаковать? Xor ключ я нашёл в игре.

**Comment by klensy** [comment]
clog_unpack -i log.clog -o unpacked.log -k key.dat

В key.dat запиши ключ в бинарном  виде.

**Comment by painka** [comment]
А если использовать *.exe file scripts?

**Comment by klensy** [comment]
Вот для них я и написал. Запусти clog_unpack, будет хелп же.

**Comment by painka** [comment]
Работает со старыми версиями, в патче 1,53 не могу найти xor ключик.

**Comment by klensy** [comment]
Проверил на 1.55.3.95, все работает.
