### ISSUE TITLE
[IMPORTANT] NEW .bin files found in 1.59 dev server game folder.

### ISSUE THREAD

**Issue by 3316556** [klensy/wt-tools#16]
there are 2 new files one is editable with notepad ++ without unpacking and looks like it has hashes of some sort within maby this file has what you need for extracting 3d models from .grp files. Idk im just a pleb, with too much free time
[New files.zip](https://github.com/klensy/wt-tools/files/296733/New.files.zip)

**Comment by klensy** [comment]
Don't know how to use it, but thanks :-)
