### ISSUE TITLE
zlib.error when trying to unpack aces.vromfs.bin

### ISSUE THREAD

**Issue by mislczxyz** [klensy/wt-tools#18]
Hello. I sucesfully installed Python 2.7, added it to PATH and ran the script to unpack the aces.vromfs.bin from the latest War Thunder release (1.61.1.45). It gave me the following output:

```
C:\Users\MISLcz\Desktop\wt-tools-master>python vromfs_unpack.py aces.vromfs.bin
Traceback (most recent call last):
  File "vromfs_unpack.py", line 190, in <module>
    main()
  File "vromfs_unpack.py", line 186, in main
    unpack(filename, dist_dir)
  File "vromfs_unpack.py", line 109, in unpack
    data, vrfs_curr_type = decomp_and_write(filename)
  File "vromfs_unpack.py", line 79, in decomp_and_write
    dec_data = decompress(f_data[0x10:])
zlib.error: Error -3 while decompressing data: incorrect header check
```

Is there any way to fix this error?

**Comment by mike10d** [comment]
Not all dagor 4.0 (war thunder's current game engine) vromfs files can currently be unpacked by WT tools. for that reason MasterModeley posted a tool that can unpack all the vromfs in the issue 7 thread https://github.com/klensy/wt-tools/issues/7 (scroll down a bit).

to use that file it is "vromfs.exe aces.vromfs.bin aces.vromfs.bin_u\"

**Comment by mislczxyz** [comment]
OK, thank you, it worked for me.

**Comment by klensy** [comment]
Yes, cant find time to update unpacker, 'cause don't play this game long time.

**Comment by klensy** [comment]
Updated in vromfs_unpacker branch (later, will tested and pushed to master)
