### ISSUE TITLE
Распаковка DDSX

### ISSUE THREAD

**Issue by diwersan7** [klensy/wt-tools#2]
При обработке blk файлов, blkx создаётся рядом с ним.
Хотелось бы видеть аналогичное и для ddsx.
Удобно для обработки всех файлов через bat
![image](https://cloud.githubusercontent.com/assets/13134670/8455269/b103aa64-2003-11e5-9266-533a76eb0d75.png)

**Comment by klensy** [comment]
Ок, сделаю как и для blk, возможность указать папку, в которой все ddsx будут преобразованы, что-то типа этого: `ddsx_unpack folder_with_ddsx`

**Comment by diwersan7** [comment]
Не по теме: 
Что прочить по данной теме
Хотел бы разобраться с принципом работы

**Comment by klensy** [comment]
>Хотел бы разобраться с принципом работы

С принципом работы чего, питона, скриптов, dds?
Если питона, то есть КУЧА книжек, dive into python например.
Если скриптов - то читай исходники.
По dds'у тоже доки есть,  например [тут](https://msdn.microsoft.com/en-us/library/windows/desktop/bb943991%28v=vs.85%29.aspx).

**Comment by diwersan7** [comment]
По поводу питона, для начала
Спасибо

**Comment by diwersan7** [comment]
вряд ли сильно помог, но переделал чтоб сохраняло рядом с исходным файлом

**Comment by klensy** [comment]
Хех, я тоже уже сделал, сейчас загружу. Можно натравливать на папку с ddsx файлами.

**Comment by diwersan7** [comment]
В питоне я 0, так что натравливать на папку я не смог
Рад слышать
Ждем
