### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by 3316556** [klensy/wt-tools#20]
It would be fantastic if the blk_unpack.exe could, after unpacking the .blks, it would have an option to output the .blks as .blk instead of .blkx and delete the old .blks automatically. Thank You. :)

**Comment by hairypaulsack** [comment]
Everybody that does this most likely uses batch scripts. Your request [IMO] is a waste of the authors time and not going to happen, though I may be wrong. What you are supposed to do in this situation, I use your brain and critical thinking. I went from knowing nothing about batch scripting to all of this in about an hour. I will not explain this for you, and this will not work for you. I put some hints down below on what some things might mean, but you are going to have to use your brain for this one and ask questions or better yet, just read the questions that have already been asked. If you do come back and ask for help, I will explain things for you so you can understand and get you set up to auto extract and convert

```
ROBOCOPY "D:\WarThunder" "D:\WT-TOOLS\WORKING-DIR\VROMFS.BIN_U" "*.vromfs.bin"
FOR %%f IN (*bin) DO vromfs_unpacker "%%f"
FOR /R %%f IN (*blk) DO blk_unpack --strict_blk "%%f"
ROBOCOPY "D:\WT-TOOLS\WORKING-DIR\VROMFS.BIN_U" "D:\WT-TOOLS\WORKING-DIR\.BLKX_ONLY" "*.blkx" /S /MOV
```
