### ISSUE TITLE
vromfs_unpack is not working

### ISSUE THREAD

**Issue by diwersan7** [klensy/wt-tools#22]
Не хочет распаковывать aces.vromfs.bin
Может ошибка во мне, ибо я давно не пользовался, но тем не менее
![image](https://cloud.githubusercontent.com/assets/13134670/19746335/3c605ac2-9bd6-11e6-943b-6b993e68505e.png)

**Comment by klensy** [comment]
Я ультраленив. Попробуй https://github.com/klensy/wt-tools/files/56376/vromfs.zip

**Comment by diwersan7** [comment]
Работает)
Но однажды лень нас всех погубит
