### ISSUE TITLE
Help needed - WT not using extracted files

### ISSUE THREAD

**Issue by xennex22** [klensy/wt-tools#27]
I have extracted aces.vromfs.bin and gui.vromfs.bin, but cannot get WT to use the extracted files over the original binaries.
If I delete the original .bin file then WT will re-run the launcher and download the ,bin again.
I've tried placing the extracted files in the WT directory, under aces.vromfs.bin_u (as a directory) and various combinations.  I used procmon to look where WT was loading the files, and moved them accordingly, but this did not help.
Is the ability of WT to load the files disabled now?

**Comment by klensy** [comment]
WT never used extracted files as replace for *.vromfs.bin files (as i know).

**Comment by xennex22** [comment]
Thanks for the reply.  Do I need to repack the files then? Or is this something which wt-tools is not designed to do (research only)?

**Comment by klensy** [comment]
Mainly - research. And binaries (*.vromfs.bin) looks like (crypto) signed, so we cant just replace them.

**Comment by xennex22** [comment]
If this is a direction you'd like to go, I'll share anything I find.  Otherwise, thanks for your help.
