### ISSUE TITLE
Проблема с Mip-Map

### ISSUE THREAD

**Issue by FozeSt** [klensy/wt-tools#28]
Такая беда, хотел дернуть немного fx текстур, так они сразу с Mip-Map уровнями накладываются и иногда сползают с середины
Вот кароче говоря http://i.imgur.com/zRDcRyW.png

**Comment by klensy** [comment]
Иногда криво распаковывает. Качни [warthunder cdk](https://wiki.warthunder.ru/index.php?title=%D0%A1%D0%BA%D0%B0%D1%87%D0%B0%D1%82%D1%8C_War_Thunder_CDK), запусти и попробуй взять текстуры оттуда.

**Comment by FozeSt** [comment]
Окей, спасибо
