### ISSUE TITLE
Exe download broken

### ISSUE THREAD

**Issue by 3316556** [klensy/wt-tools#30]
I get a failed - network error

**Comment by klensy** [comment]
It works for me, try again: https://github.com/klensy/wt-tools/releases/download/0.2/wt-tools.rar

**Comment by 3316556** [comment]
https://gyazo.com/f6f68f63163b3358121c87d5edbbff68 nope

**Comment by klensy** [comment]
Don't know what's wrong, should work. Just uploaded here for you http://rgho.st/854BDfpy7

**Comment by 3316556** [comment]
That link didn't work either, so I tried downloading from my phone and the github link worked. idk why I didn't think of that in the first place. Sorry I wasted your time, and Thank you for being so helpfull! :)

**Comment by 3316556** [comment]
I was having issues dragging exe files to desktop, they were being deleted by avast turns out it thinks its a virus lol

**Comment by klensy** [comment]
Yes, https://www.virustotal.com/en/file/119a9f8f637ec75077fb4bbefb0f19c1d63377ea0748ff795c1d50344599f02a/analysis/ avast is angry. No viruses, at least mine ;-)
