### ISSUE TITLE
Проблемы с анпакером WT

### ISSUE THREAD

**Issue by TauKion** [klensy/wt-tools#32]
Перестала работать сборка под анпак .vromfs.bin процес прекращается/не начинается. Сами файлы прилагаю.

[1.69.1.2.zip](https://github.com/klensy/wt-tools/files/1014474/1.69.1.2.zip)

**Comment by klensy** [comment]
Все пашет, ты использовал старую версию. Качаешь из <a href="https://github.com/klensy/wt-tools/releases">releases</a> последнюю и все работает.
