### ISSUE TITLE
Update 1.69 broke the unpacker again.

### ISSUE THREAD

**Issue by 3316556** [klensy/wt-tools#34]
This time its not returning any errors
https://gyazo.com/d95ffde5bd2da92b6324e35ab5c2cc31

I tried the old Vromfs_unpacker.exe and it works again but it doesn't unpack some of the folders.
https://gyazo.com/375cf7def91ad10bfdd6f6cf2723d2db

**Comment by 3316556** [comment]
just saw the new Bug issue oops

**Comment by klensy** [comment]
U use ```vromfs.exe```, but u should use ```vromfs_unpacker.exe``` instead. Should work, use old https://github.com/klensy/wt-tools/releases/tag/0.2

**Comment by 3316556** [comment]
oh works now for some reason. Thanks!
