### ISSUE TITLE
0.2.1.1 still working with 1.75.0.99?

### ISSUE THREAD

**Issue by Magicool-1** [klensy/wt-tools#36]
Hey

I can't seem to unpack .clogs from Prod 1.75.0.99 with wt tools 0.2.1.1.
I drag and drop the file onto the clog_unpack.exe but nothing happens after the cmd window closes.
Theres no unpacked files.
Using the windows binaries.

**Comment by klensy** [comment]
I did not provide keys intended, for log xoring, so it will not work this way.
