### ISSUE TITLE
add 1.83 support

### ISSUE THREAD

**Issue by MuhAbroomz** [klensy/wt-tools#39]
with 1.83 update the file formats of the game is changed so some files(like ddsx) are not unpackable. can you update the WT tools and add 1.83 support?
PS. I want to know how to unpack .grp files.

**Comment by klensy** [comment]
Hi. Can u upload vromfs files from 1.83, that can't be unpacked? Problem with ddsx is known - some ddsx files wont unpack properly.

**Comment by MuhAbroomz** [comment]
i checked again and only ddsx was not unpacked. so...yeah, anything else had no problem. another question: will there be an updated version of ddsx unpacker?

**Comment by MuhAbroomz** [comment]
[ger_cruiser_prinz_eugen.dxp.bin_u.zip](https://github.com/klensy/wt-tools/files/2507316/ger_cruiser_prinz_eugen.dxp.bin_u.zip)
can you unpack these ddsx files?

**Comment by MasterModeley** [comment]
Now for compression it is used oodle instead of lzma.

**Comment by MasterModeley** [comment]
New texures https://yadi.sk/d/5wwpClSBdSCsnA

**Comment by Verifirs** [comment]
Could be possible to use this to solve the problem? https://github.com/powzix/ooz

**Comment by klensy** [comment]
Added support, should work now.
