### ISSUE TITLE
Unable to unpack .Clog files?

### ISSUE THREAD

**Issue by ThatZenoGuy** [klensy/wt-tools#42]
Please understand I am not very knowledgeable about programming and all, but I'm willing to learn some stuff.

Unpacking .clog files seems to need some sort of key file? How do I get this? I would like to know.

**Comment by diVineProportion** [comment]
https://github.com/klensy/wt-tools/issues/35#issuecomment-339932745

as for that key, try google bro..

**Comment by diVineProportion** [comment]
@ThatZenoGuy 

watch some videos on python bytes, bytearrays, and writing files in the 'wb' (write binary) mode. You could also close this issue, since it's not an issue
