### ISSUE TITLE
BLK FILES NOT EXTRACTING IN CORRECT FORMAT

### ISSUE THREAD

**Issue by a1121119629** [klensy/wt-tools#44]
Hello, I noticed that someone mentioned this question before. You answered this question, but I still don't know how to operate it. Can you tell me a course? I read your answer through translation software. I can't get the correct result through your short answer. The language barrier makes it very difficult for us to communicate. Please tell me the operation steps as detailed as possible. Thank you very much.

**Comment by klensy** [comment]
Hi, what exactly you want?

**Comment by a1121119629** [comment]
![QQ图片20190313162822](https://user-images.githubusercontent.com/48510116/54263991-10801900-45ad-11e9-952f-1815ca024dfc.jpg)

**Comment by a1121119629** [comment]
![QQ截图20190313163319](https://user-images.githubusercontent.com/48510116/54264304-c186b380-45ad-11e9-94a8-429c740ebc39.png)
Excuse me, how does this function work?

**Comment by klensy** [comment]
1. Download windows build from https://github.com/klensy/wt-tools/releases (get latest version, dev).
2. Unpack wt-tools.zip to some folder.
3. Copy files you want to unpack to this folder.
4. Drag and drop *.vromfs files on vromfs_unpacker: this will unpack vromfs (or you can run ```vromfs_unpacker.exe somefile.vromfs.bin``` from console)
5. Unpack blk: run ```blk_unpack.exe --format=strict_blk somefile.vromfs.bin_u``` where ```somefile.vromfs.bin_u``` - unpacked vromfs folder

**Comment by klensy** [comment]
If you run ```blk_unpack.exe -h``` then will be printed little help.

**Comment by klensy** [comment]
If you don't know how to open console in folder, see [there](https://superuser.com/questions/339997/how-to-open-a-terminal-quickly-from-a-file-explorer-at-a-folder-in-windows-7)

**Comment by klensy** [comment]
So, left version you can get with ```blk_unpack.exe --format=json somefile.vromfs.bin_u```, right version with ```blk_unpack.exe --format=strict_blk somefile.vromfs.bin_u``` (from your first screenshot). ```somefile.vromfs.bin_u``` can be folder with blk's or one blk file for unpacking.

**Comment by a1121119629** [comment]
I want to create a custom task. I need a BLK file that can be read by the game.  Using blk_unpack.exe directly to get the BLKX file, as in the left side of the picture I just posted, I need to know  how to get the format on the right side.

Thank you so much for your help. It took me a week to solve this problem.

**Comment by a1121119629** [comment]
I'm sorry, because of the difference between the language and the system. (Seems to be WINXP for your see there?  I'm using WIN10, but it's still hard for me to understand.  The meaning expressed in steps 4-5.            I know very well how to get the file on the left (from my first screenshot) and just drag the specified file to (blk_unpac k.exe) to get a BLKX file (this file is useless).            I want to get the file on the right (from my first screenshot).  This is the format that can be read by the game.            I think I'm probably a little more dumb than the other questioners.  Because I'm not a code developer            If you teach me how to get the right file, I'll be very grateful to you and willing to pay (if there is a convenient and f ast way to pay)
![QQ图片20190313172113](https://user-images.githubusercontent.com/48510116/54268564-7624d300-45b6-11e9-9c70-a2311f994377.jpg)

**Comment by a1121119629** [comment]
I can't speak English, the translation of translation software is not accurate, and I'm very confused about communicating with your text. I'm trying to understand and look up information. Maybe I need guidance from a graphic or video tutorial.            You can go on answering my questions. Or stop answering. Never mind, you told me a lot of valuable information, but I am too stupid to understand, I will continue to learn, thank you!

**Comment by klensy** [comment]
As noted [here](https://superuser.com/questions/339997/how-to-open-a-terminal-quickly-from-a-file-explorer-at-a-folder-in-windows-7):
1. holding shift, right click on empty space in folder, then select ```open command window here```
2. In opened window insert command```blk_unpack.exe --format=strict_blk aces.vromfs.bin_u```

**Comment by klensy** [comment]
Download [this](https://gist.githubusercontent.com/klensy/10e02e92f2d88c739b500616a83e285f/raw/1dfd5ae56e7525f86d333dbb4b4de980a155d336/unpack_blks.bat) file to your folder and run.

**Comment by a1121119629** [comment]
![QQ图片20190313181852](https://user-images.githubusercontent.com/48510116/54271576-c010b780-45bc-11e9-9895-8166789f29a3.png)
![QQ图片20190313181944](https://user-images.githubusercontent.com/48510116/54271578-c010b780-45bc-11e9-80c1-2fcf255594ef.png)
The "blk_unpack.exe" item cannot be recognized as the name of a cmdlet, function, script file, or runnable program. Please check the spelling of the name if it includes            Path, please make sure the path is correct, and try again.            Location line: 1 character: 1

**Comment by a1121119629** [comment]
Successful. Thank you so much.

![Uploading QQ图片20190313182630.png…]()
