### ISSUE TITLE
Cuisine Royale

### ISSUE THREAD

**Issue by CrIcKeT98** [klensy/wt-tools#46]
Привет! Нету ли у тебя в планах заняться распаковкой ресурсов игры Cuisine Royale (он же Enlisted)? База у них, что и с War Thunder, одна. Даже Asset Viewer из пакета War Thunder CDK может открывать контент Cuisine Royale, но не HQ. Его он не видит вовсе и твои инструменты могут лишь распаковать HQ паки, но с текстурами уже проблема, там какой-то иной алгоритм компрессии текстур. Может, могу как-то помочь?

**Comment by CrIcKeT98** [comment]
С выходом обновления 1.97 War Thunder тоже перешёл на HQ текстуры и wt tools не может конвертировать эти текстуры в DDS

**Comment by klensy** [comment]
Привет. Это та же компрессия, что и в и #39, так что пока никак. Warthunder CDK обновилось, попробуй http://cdk.warthunder.com/WarThunderCDK_2020_03_16__19_46.exe

**Comment by CrIcKeT98** [comment]
Да, я знаю что обновилось, однако WT и CR используют алгоритмы для паков HQ (vromfs). Если взять HQ пак CR и положить его в папку со всеми HQ паками WT под уже существующем именем, то CDK выдаст ошибку хедера файла. Также WT CDK не умеет подтягивать дополнительные внешние HQ паки. Если что, в данный момент используется OODLE компрессия, но я не знаю для чего именно она используется (для паков или текстур).

**Comment by Twisted6** [comment]
I'd also like to be able to unpack the Cuisine Royale stats.

**Comment by klensy** [comment]
Hi, i added support for basic support of Cuisine Royale: vromfs files can be unpacked, but not textures yet. https://github.com/klensy/wt-tools/releases

**Comment by Twisted6** [comment]
> Hi, i added support for basic support of Cuisine Royale: vromfs files can be unpacked, but not textures yet. https://github.com/klensy/wt-tools/releases

Thank you very very much for your quick response, it works perfectly for my needs :)  I'll credit you for the tool in my stats sheet.

**Comment by klensy** [comment]
Bot names (pretending to be players ?): cuisine_royale\ui.vromfs.bin_u\gamedata\names\generated_names.nut

**Comment by Twisted6** [comment]
> Bot names (pretending to be players ?): cuisine_royale\ui.vromfs.bin_u\gamedata\names\generated_names.nut

Yep. Solo queue has bots.

**Comment by klensy** [comment]
Added support for oodle textures, should work now, but again - not always.
