### ISSUE TITLE
Enlisted Vromfs FIle Support.

### ISSUE THREAD

**Issue by mogley25** [klensy/wt-tools#47]
Hello. Can you add datamining support for the game Enlisted that Gaijin did an Alpha Test recently?
Heres the link to the base game file. https://drive.google.com/file/d/1YrjsSGKy72NOOOcBwTlUSHFbgsbZHQdF/view?usp=sharing

**Comment by klensy** [comment]
Hi, it's already opens this vromfs.bin format.

**Comment by mogley25** [comment]
> Hi, it's already opens this vromfs.bin format.

Me and a few other buddies tried it. It does not work. Gaijin changed the file encoding or something. The window immediately closes.

**Comment by klensy** [comment]
Check latest build (https://github.com/klensy/wt-tools/releases/tag/v0.2.2.2), it works.

**Comment by mogley25** [comment]
> Check latest build (https://github.com/klensy/wt-tools/releases/tag/v0.2.2.2), it works.

Thank you. I'm very blind lol. Sorry for the unneeded issue ticket.
