### ISSUE TITLE
Cannot extract unit icon *.ddsx despite using oo2core_6_win64.dll

### ISSUE THREAD

**Issue by JareelSkaj** [klensy/wt-tools#49]
Hi, I have a new version of the [wt-tools v0.2.2.2-dev](https://github.com/klensy/wt-tools/releases/tag/v0.2.2.2) and cannot extract any of the *.ddsx files in the `WarThunder\ui\atlases.vromfs.bin_u\units`, eg `a_4b.ddsx`. Tool just blinks open, and nothing happens.
I have installed Warframe and coped over `oo2core_6_win64.dll` into the directory with the ddsx_unpack.exe [as suggested here](https://github.com/powzix/ooz) ([from](https://github.com/klensy/wt-tools/issues/39#issuecomment-573273101)), but that did not help either. Though I should note that my file is from the latest version of the Warframe and has an MD5 of `9a118e80ae34d02bbadf0af6b12082f6` (byte size 1 074 176, via `CertUtil -hashfile oo2core_6_win64.dll md5`), different that the one [specified](https://github.com/klensy/wt-tools/releases/tag/v0.2.2.2) in the release. If needed I can provide the dll, though I have no idea where can I find the it with the MD5 indicated in the release to check if that's the source of the issue ¯\_(ツ)_/¯.

Windows 10 x64, Intel i7-8700K

**Comment by klensy** [comment]
1. Try to run tool in powershell (open directory with *.exe files, shift+right click on empty space, powershell: https://www.youtube.com/watch?v=bgSSJQolR0E), then enter here `ddsx_unpack.exe atlases.vromfs.bin_u`. If any errors, int should be printed.
2. oo2core_6_win64.dll should be near ddsx_unpack.exe and other *.exe files.

**Comment by klensy** [comment]
@JareelSkaj Any progress?

**Comment by JareelSkaj** [comment]
Sorry, I was out.
Yes, it did work!
Wow... I did not see this coming. Really appreciate fast response.
