### ISSUE TITLE
del

### ISSUE THREAD

**Issue by amaxcz** [klensy/wt-tools#5]
подскажите пожалуйста, где брать decryption key?

**Comment by klensy** [comment]
Нашел?

**Comment by amaxcz** [comment]
ага.  пофигси пожалуйста распаковщик wrpl если не трудно

благодарю тебя
06 Авг 2015 г. 19:16 пользователь "klensy" <notifications@github.com>
написал:

**Comment by klensy** [comment]
Ну так дай wrpl файл, пофикшу )

**Comment by amaxcz** [comment]
вот, пожалуйста.. версия видимо изменилась

2015-08-06 19:20 GMT+02:00 klensy <notifications@github.com>:

**Comment by klensy** [comment]
Залей на ргхост или куда еще, иначе вложения не увижу.

**Comment by amaxcz** [comment]
вот так например
https://dl.dropboxusercontent.com/u/7411648/%232015.08.06%2017.15.28.wrpl
прямая ссылка

2015-08-06 19:32 GMT+02:00 klensy <notifications@github.com>:

**Comment by klensy** [comment]
Не надо было стирать название, просто закрыл бы. Готово, распаковывает, вот только обновил питон версию, exe'шник соберу позже.

**Comment by amaxcz** [comment]
благодарю! название исправил ;)

6 августа 2015 г., 19:50 пользователь klensy <notifications@github.com>
написал:
