### ISSUE TITLE
Cannot unpack most .ddsx files

### ISSUE THREAD

**Issue by OfficialDSplayer** [klensy/wt-tools#52]
Using the current v0.2.2.5-dev release doesn't allow for most .ddsx files to be unpacked with vehicle textures along with the UI textures not being able to be unpacked.

**Comment by klensy** [comment]
Hi. Any error message if you ran tool from commandline? I think you missed
>To turn on this feature, you should place oo2core_6_win64.dll file to wt-tools directory, near ddsx_unpack.exe

**Comment by OfficialDSplayer** [comment]
I didn't see the "oo2core_6_win64.dll" and it wasn't included in the "easy way" download so I decided to download it from a separate site and it seems to have worked.
