### ISSUE TITLE
[Feature Request]: Re-Pack extracted files

### ISSUE THREAD

**Issue by RumoOr** [klensy/wt-tools#55]
Is that even possible? Would be nice to be able to pack already extracted files into original format. 
For example, extracting .nut scripts from vromfs.bin, modify them, pack them again. I guess its not possible or even when, signing isnt the same anymore right?

**Comment by klensy** [comment]
Hi.
It was asked few times already, as u can assume )
Even if it possible repack vromfs back, yes, we can't sign it and until devs allow modifications, it can lead to ban. Main issue here is word from devs.

**Comment by RumoOr** [comment]
yeah, allready asumed to here that. to bad...
