### ISSUE TITLE
Wprl_unpacker.exe doesnt work anymore 1.99

### ISSUE THREAD

**Issue by mogley25** [klensy/wt-tools#56]
so im trying to unpack a replay but the cmd just opens and closes. It worked before but gaijin must have changed something.

**Comment by mike10d** [comment]
I have looked into it a little bit and there appear to be two issues with replay unpacking right now.

1. the version number for the replay has changed so it will fail when it tries to match the replay file's version number to the `wrpl_version` enum.

from the replay.wdb (found in the WT replays folder) we can see the new replay version number is `101033` or `0xA98A01`

![image](https://user-images.githubusercontent.com/15133730/89259926-52be5600-d5f9-11ea-9dc4-50ff508154a4.png)



2. the offset of the m_set blk has changed to 0x444 in 1.99 replays.

![image](https://user-images.githubusercontent.com/15133730/89258734-b5622280-d5f6-11ea-9ea4-574e1be132b7.png)

I would also note that currently the `wrpl_parser.py` file currently reads the `wrpl_version` as Int16, but the replays.wdb file's version number is at least Int24 long, and could be Int32 long.

**Comment by mogley25** [comment]
Can I ask what program you used to see the binary of the replay file and what extractor did you use to see the replay.wbdx file?

**Comment by klensy** [comment]
Yeah, this thing broken some time ago, will fix.

**Comment by klensy** [comment]
Fixed.
