### ISSUE TITLE
Где ключ?

### ISSUE THREAD

**Issue by boartem** [klensy/wt-tools#61]
Есть инструментарий для открытия *.clog файлов. В инструкции сказано про некий файл keyfile.bin, но где его можно найти?

**Comment by boartem** [comment]
Ладно, мне удалось найти ключ (-c 0x20 и -l 128). Но может есть еще более точный, по скольку где то 1-2% информации отображается не корректно.

**Comment by klensy** [comment]
Привет, ключ не клал с самого начала; точный ключ можешь получить просто поискав уже известный кусок в экзешнике игры.
