### ISSUE TITLE
Convert blk to json format

### ISSUE THREAD

**Issue by Stiffi136** [klensy/wt-tools#63]
Hi,
First of all, thanks for the great tool set you provide here.
I'm trying to convert blk files to json format. I read that it should be possible to output blk files in json by using `blk_unpack --format=json`. However no format option seems to work: https://i.imgur.com/XXvzouW.png . I tried this with the latest dev release. Am I doing something wrong, or is it not intended to be used like this?

**Comment by klensy** [comment]
Hi.
blk_unpack only decode binary blk format (BBF in file start) to text representation (json or txt), not to convert between json <-> text.

**Comment by Stiffi136** [comment]
Thanks for the quick response. I suppose I'll have to parse it with other methods then.
