### ISSUE TITLE
Using GPU to extract/unpack

### ISSUE THREAD

**Issue by OshidaBCF** [klensy/wt-tools#67]
Please excuse me if this is the dumbest idea you ever heard.

But would it be possible to use the GPU instead of the CPU for decoding the files ?

Maybe even using both ?

**Comment by X1Zeth2X** [comment]
You might want to check this: https://github.com/facebook/zstd/issues/2307

**Comment by OshidaBCF** [comment]
okay thanks.

i was "dreaming" for faster ... things... with a gpu, but i guess i'm dreaming too much
