### ISSUE TITLE
REPACK

### ISSUE THREAD

**Issue by 3316556** [klensy/wt-tools#8]
Is there any way to reverse the unpacking process? I'm trying to make a custom plane in the cdk.

**Comment by mike10d** [comment]
There are official tools to import a plane into the game.
http://wiki.warthunder.com/index.php?title=3D_models_for_aircraft

http://wiki.warthunder.com/index.php?title=General_information_about_model_creation_for_Dagor_Engine

**Comment by 3316556** [comment]
You so much! i cant wait to replace the turrets guns on the B-29 with 152mm howitzers! dont worry i don't do server side shenanigans. :D

**Comment by 3316556** [comment]
also is their an easyer way to after unpacking a planes flight model blk to repack it with your program?

**Comment by klensy** [comment]
Yes, you can change blk and fly on test mission with it, see on wt-live.
I can't understand your last message, sry.

**Comment by 3316556** [comment]
i need to be able to convert this http://imgur.com/EWy6Ele to this http://imgur.com/eDY75Oz and back this http://imgur.com/EWy6Ele with my edited peramiters because when i put the edited unpacked flightmodel back into the game it says there is a missing { when i know i did not move or deleate a {

**Comment by klensy** [comment]
Ahh, i understand, need to find some time for it.

**Comment by 3316556** [comment]
Thank you for being such a great developer! :D

**Comment by klensy** [comment]
U can try this: http://live.warthunder.com/post/214882/ as example of custom plane.

**Comment by 3316556** [comment]
well yeah thats the thing ive been trying to edit the flight model file from another custom plane like this one from the same uploader http://live.warthunder.com/post/188466/en/ this one comes with everything the only thing is he knows how to repack the flightmodel.blk ill try contacting him on steam. in the meantime id like to show you some things i've found using your wonderful tools, if your interested send me an email at sterlingarcher2525@gmail.com with your skype,facebook,curse or steam username. :)

**Comment by klensy** [comment]
I think, that all what you found, already revealed on reddit or wt official forum, but you cant try to post there https://www.reddit.com/r/Warthunder/ anyway.

**Comment by 3316556** [comment]
no i mean like ive found the all the server ip addresses (which i would like to see you remove the ability to unpack that file, because of ddosers) and i found out how to drive the ships and shoot the guns, i found a mission blk that is a demo for ipads. i took the android version and decompiled it to find a file called loadinganim_cock.ddsx (well done gaijin XD) and once i find out how to recompile the blks ill be able to put a maus turret on top of a b29.

**Comment by 3316556** [comment]
![image](https://cloud.githubusercontent.com/assets/15257201/10724412/a1449ece-7b81-11e5-9066-9bf9176d76c7.png) i think i broke the game

**Comment by klensy** [comment]
Speed overflow i see on this pic.

**Comment by mike10d** [comment]
When I talked to you on reddit klensy you said WT checks file file integrity, and I think it just looks at file length which seems to be stored in /content/warthunder.blk, so I think if you were to repack a .vromf.bin file you would have to change the file size listed in that file.

**Comment by klensy** [comment]
Vromfs file ends with some sort of control sum.

**Comment by mike10d** [comment]
oh, interesting thanks for the info.

**Comment by 3316556** [comment]
so it wont work? or..

**Comment by 3316556** [comment]
Also you can skip the file check by opening warthunder with the aces.exe instead of the launcher. :)

**Comment by mike10d** [comment]
No the game will still check file integrity of .vromf.bin files even if you just launch aces.exe

**Comment by 3316556** [comment]
shit

**Comment by jalba69** [comment]
If the packed .vromf.bin file is used in the "pkg_user" folder for a custom plane it shouldn't matter much, like for the rest of the user created content.

It will be nice to be able to pack some blk files into a .vromf.bin file when creating a plane model, you could have a single file for the plane blk's instead of various blk's for the plane fm file, the various armament presets etc , if only it was possible to export all the blk's into the dxp.bin file when exporting the textures it will be easier.

**Comment by klensy** [comment]
*dxp.bin files contains only textures (as long as i can see).

**Comment by 3316556** [comment]
any progress on the repack ability?

**Comment by klensy** [comment]
No progress until new patch, where vromfs format will be changed.

**Comment by 3316556** [comment]
:L neat!

**Comment by 3316556** [comment]
noo the tools don't work for the new update!

**Comment by klensy** [comment]
Yes, as mentioned there #7.

**Comment by 3316556** [comment]
if you need any files from the previous update i have a backup

**Comment by 3316556** [comment]
any progress?

**Comment by i1128928** [comment]
@3316556, It is not necessary to convert text blk to binary blk. The game can read both formats. And your [file](http://imgur.com/eDY75Oz) is written in JSON format. That is why you have got error message about "{" when you put it into the game. You should not unpack blk as JSON.
Ex, how j-21-a1.blk looks in a text form:
```
takeoffDistance:r=266.351
landingDistance:r=266.351

altSpecs{
  altSpecs0{
    maxSpeed:r=149.799
    optSpeed:r=73.4
    maxClimb:r=23.4287
  }

  altSpecs1000{
    maxSpeed:r=153.999
    optSpeed:r=73.4
    maxClimb:r=23.141
  }

  altSpecs2000{
    maxSpeed:r=154.999
    optSpeed:r=73.4
    maxClimb:r=22.7284
  }

  altSpecs3000{
    maxSpeed:r=164.999
    optSpeed:r=73.4
    maxClimb:r=22.3889
  }

  altSpecs4000{
    maxSpeed:r=171.199
    optSpeed:r=73.4
    maxClimb:r=21.8539
  }

  altSpecs5000{
    maxSpeed:r=177.599
    optSpeed:r=73.4
    maxClimb:r=21.4505
  }

  altSpecs6000{
    maxSpeed:r=183.398
    optSpeed:r=73.4
    maxClimb:r=19.2363
  }

  altSpecs7000{
    maxSpeed:r=187.598
    optSpeed:r=73.4
    maxClimb:r=15.2023
  }

  altSpecs8000{
    maxSpeed:r=183.398
    optSpeed:r=73.4
    maxClimb:r=12.0369
  }

  altSpecs9000{
    maxSpeed:r=179.198
    optSpeed:r=73.4
    maxClimb:r=9.26538
  }

  altSpecs10000{
    maxSpeed:r=173.599
    optSpeed:r=73.4
    maxClimb:r=6.40192
  }

  altSpecs11000{
    maxSpeed:r=166.999
    optSpeed:r=73.4
    maxClimb:r=3.58328
  }
}
```

**Comment by klensy** [comment]
@i1128928, yes `blk_unpack --strict_blk some_file.blk`.

**Comment by 3316556** [comment]
thank you
so much!

**Comment by jalba69** [comment]
>klensy 

>*dxp.bin files contains only textures (as long as i can see).

Yeah, sadly, it had been good to have some possibility to repack everything into a single file for having planes models into a single package.

Good to see you are making some progresses with all this, keep up the good work.
