### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by danielsoftwaree** [klensy/wt-tools#81]

**Comment by FlareFlo** [comment]
The file is a binary BLK file https://pastebin.com/yLEJJG47

**Comment by helpsebe** [comment]
> The file is a binary BLK file https://pastebin.com/yLEJJG47

Amazing! I saw the link, but probably made a mistake somewhere in saving the file. I already tried to use wt-tools from @kotiq, but got an error.

How did you manage to do it? This is a very interesting experience for me

**Comment by FlareFlo** [comment]
I used [my unpacker](https://github.com/Warthunder-Open-Source-Foundation/wt_blk) that i developed with the documentation and information about BLK from kotiq, though it specializes for VROMF unpacking.

**Comment by helpsebe** [comment]
> The file is a binary BLK file https://pastebin.com/yLEJJG47
Can you help me with unpacking blk? I'm running into errors. Can you tell me how you managed to convert to text?

**Comment by helpsebe** [comment]
> I used [my unpacker](https://github.com/Warthunder-Open-Source-Foundation/wt_blk) that i developed with the documentation and information about BLK from kotiq, though it specializes for VROMF unpacking.

I'm not very familiar with the Rust language environment. Can you give me a quick tutorial? Thank you!

**Comment by helpsebe** [comment]
![image](https://github.com/klensy/wt-tools/assets/19814545/865e4609-77a2-4da1-ae7b-77f898171ea4)

**Comment by FlareFlo** [comment]
The command for unpacking standalone BLK files in the CLI tool is currently unstable and disabled. I will try to stabilize it soon. I unpacked the BLK you provided "by hand"

**Comment by helpsebe** [comment]
SOLVED:

It was a BLK binary file.
The first byte 0x01 indicated a FAT file type (usually BBF) which indicates that the file is self-contained, it already contains a NameMap.

I found all the information here: [kotiq/wt-tools](https://github.com/kotiq/wt-tools) (there are also docs about Binary BLK).

Special thanks to @FlareFlo

**Comment by Sgambe33** [comment]
> Hey, everybody.
> 
> I've only recently started researching WT, but I've already come across a question that I can't find an answer to yet. I managed to get a file - [link](https://github.com/helpsebe/wt-research/raw/main/userinfo.txt) , but it is missing values. It looks like a table, but I'm not sure.
> 
> also the file in binary form - [link](https://github.com/helpsebe/wt-research/raw/main/userinfo)
> 
> Server Response:
> 
> CODE:

I'm interested in the data contained in that file, where did you find it?
