### ISSUE TITLE
BLK FILES NOT EXTRACTING IN CORRECT FORMAT! [SOLVED]

### ISSUE THREAD

**Issue by 3316556** [klensy/wt-tools#9]
Flightmodel blk's and related blk files do not extract correctly, unpacked files look like this http://imgur.com/wqhyqNL when they should look like this http://imgur.com/IHWiPex for the game to recognize the blks.

**Comment by diwersan7** [comment]
blks are recognizable for game at this format
It's still at JSON format, but with another structure to access parameters

**Comment by klensy** [comment]
blk_unpack --strict_blk filename.blk

just run blk_unpack without params

**Comment by 3316556** [comment]
omg THANK YOU SO MUCH! >:D hello 5000+ hrs of mucking around!

**Comment by 3316556** [comment]
Is there a way to do the blk_unpack --strict_blk filename.blk command but unpack multiple blks at once?

**Comment by klensy** [comment]
blk_unpack --strict_blk folder

**Comment by 3316556** [comment]
Thank you kind sir!

**Comment by 3316556** [comment]
is there a command that when unpacking dxp.bin files after extraction the extracted ddsx files stay in their root folders /files like so

**Comment by 3316556** [comment]
is there any way to repack a vromfs after unpacking. i may have found a way around the file checking process?
